name: Test Login

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Install NEW Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: OIDC Login
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: |
          databricks auth login --host $DATABRICKS_HOST --oauth

      - name: Test clusters
        run: |
          databricks clusters list
