name: Test OIDC to Databricks

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Print OIDC Token Claims
        run: |
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/vdhiman0810" | jq -r '.value')

          echo "$TOKEN" | cut -d '.' -f2 | base64 -d | jq
